### ISSUE TITLE
Simultaneous 2nd game server instance (dev & campaigns)

### ISSUE THREAD

**Issue by milivojm** [CntoDev/central-plaza#5] opened 2021-01-14 23:17 UTC
We lost our "2nd server" which was a secondary VM instance called Dev Server which was able to run a simultaneous 2nd game server instance for either continuous campaigns (e.g. anti-stasi) or testing missions with their own separate server config file, cba configs and repos, so we wouldn't always have to swap between setups on the main Private Server.

**Comment by enrico-ghidoni** [comment] 2022-01-21 11:16
Duplicate of #13

**Closed by enrico-ghidoni** 2022-01-21 11:16 UTC
